# Generated by Django 4.0.3 on 2022-03-19 20:58

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='options',
            field=djongo.models.fields.JSONField(default=[1]),
            preserve_default=False,
        ),
    ]
